on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: https://sonar.xn--danieljsaldaa-tkb.com
        login: e6851fe03ffeb712894278fc8e7f0bf098f264dc